### ISSUE TITLE
File Missing

### ISSUE THREAD

**Issue by sajeel93** [scazzy/Deliti#1]
Sir, I'm using this repository  for my Online Classroom Project But Live Streaming is not working
I think, billgates.swf is missing

Could you please help me ?

Thanks

**Comment by scazzy** [comment]
Hi @sajeel93  You can rename the files `sendCaster.swf` and `receiveCaster.swf` files to `billgates.swf` and `stevejobs.swf` respectively.

In case you want to change the filenames in the code, you'd have the edit the file names used in the `.as` (ActionScript) files and rebuild/export their SWFs.
